### ISSUE TITLE
Crafting reciepes are missing

### ISSUE THREAD

**Issue by Nakopa** [AppliedEnergistics/Applied-Energistics-2#1235]
The title says most of it. If i try to click on (for example) the me controller, nothing shows up and trying to craft it anyways (cause i know the reciepe) wont give me anything. Running on my own modpack and using the latest version avaible atm. I can post a whole list of all mods if that is needed

**Comment by Zaflis** [comment]
Have you disabled channels? Recipe needs a dense cable which is disabled with that config option. You can look into making a new recipe with AE2 itself or other mod, such as minetweaker.

**Comment by ShadowsVengeance** [comment]
I am having this issue as well. Everything is uncraftable except for a couple of the aesthetic blocks (fixtures and glass) and the presses have no use.

**Comment by Zaflis** [comment]
Well at least i can't reproduce, all the recipes are still there.
appliedenergistics2-rv2-beta-27

**Comment by ShadowsVengeance** [comment]
Yeah I updated to Latest from rv2 beta-10 and It seems to have fixed the issue, OP are you using the storybook modpack?

**Comment by XBlackLeopardX** [comment]
When you have AE2 installed with mekanism V8 it causes this issue apperently its fixed in anything from beta 18 and up of AE2 but for me the recipes still never work idk why even when they are the only two mods installed

**Comment by XBlackLeopardX** [comment]
I just tested it the newer versions of both mods and found out the reason it wasnt showing recipes still is something to do with the configs with the configs from the older versions it breaks the recipes of AE2 when deleting and regenerating the configs it lets the recipes show/work

**Comment by Zaflis** [comment]
I still have this config change for AE2, because i heard it may help on some issues:
modintegration {
    ...
    S:Mekanism=OFF

I'm fine with them mods having their own recipes. This config should make no change on ME interfaces, storage bus's etc connected to Mekanism machines still working, if i've understood right. The last major update was fairly big and still new.

**Comment by XBlackLeopardX** [comment]
I tried the mekanism=off and for me it didnt work but in your case things may be different

**Comment by thatsIch** [comment]
Post modlist in pastebin

**Comment by XBlackLeopardX** [comment]
Mod list of my private modpack
http://pastebin.com/ycu5QpSx

The problem i was having earlier was that the configs broke it for some reason i had to remove them and regenerate them this time though it was that I enabled the custom recipes but forgot to put the recipe files in the config thats why the recipes quit working this time i just disabled custom recipes now and its working

**Comment by Nakopa** [comment]
Got a Fix(may be temporary lol): Update to ae2-rv2 beta 27.. Reciepes are back again

**Comment by thatsIch** [comment]
There are entries in the old recipe files, which are still not working with Mekanism for some unknown reason. In the newer versions of AE2, I marked them as comments with #bug

It was just a quick fix before more than 50 issues were opened with people crying, that Mekanism destroyed AE2.

Also posting a modlist without its version is pretty useless.
If you are on windows, browse the `/mods` folder and open the command line there and execute
`dir > modlist.txt`
