### ISSUE TITLE
Facades show receipe correctly with anchors but cant be crafted

### ISSUE THREAD

**Issue by ozhound** [AppliedEnergistics/Applied-Energistics-2#2448]
Forge Version - 2095

With a fresh build we get the following error.  Cable Anchors can be crafted, but when they are placed in the crafting grid in the AE system with a block, the output receipe renders correctly but only cables are produced with a red 0 next to them.

In a standard crafting table, on shift click, the output receipe appears momentarily in the players inventory but then the process seems to revert back to the 4 cable anchors and block. if selected manually the facade is picked up at the players mouse pointer but reverts back almost instantly

this was attempted with polished granite and stone

server error - https://paste.ubuntu.com/23298739/

screenshots
![image](https://cloud.githubusercontent.com/assets/3649237/19221311/6699328e-8e73-11e6-9867-f96d3abe0265.png)

![image](https://cloud.githubusercontent.com/assets/3649237/19221315/7ca1f962-8e73-11e6-9f8c-bfd745ad846c.png)

**Comment by shartte** [comment]
Please also provide the version of AE2 that was used.

**Comment by ozhound** [comment]
My apologies.
1.10 branch Commit 6369cef

thanks

**Comment by ozhound** [comment]
Oh noes

**Comment by shartte** [comment]
It'll probably mean that the "default" is more restrictive in terms of what can be made into a facade, while it'll rely on modpack authors to make the manual config changes required for anything the default doesn't consider viable.
We'll see...

**Comment by shartte** [comment]
Should be fixed now. Please remove your Facades.cfg to make sure it updates with the new defaults. I think bone and slime block may be new, although slime doesn't render translucency.

**Comment by ozhound** [comment]
Please consider reopening this. It still doesn't work server side.

Single player works, facades can be recreated and placing them renders the
facade correctly in the correct spot, i created a brand new server so that
it would eliminate any incompatibilities but the behaviour is still the
same.

Note that cheating the facades in does work and they can be used as
expected.

https://paste.ubuntu.com/23322262/

**Comment by yueh** [comment]
Works fine for me.

**Comment by ozhound** [comment]
on a dedicated server?
