### ISSUE TITLE
Client crash searching @applied in JEI

### ISSUE THREAD

**Issue by RealGrep** [AppliedEnergistics/Applied-Energistics-2#2557]
#### Description
With the most recent update, I get a client crash when searching for @applied in JEI. The stack trace has Botania in it, so I thought to report it there. The problem could well be there, and if it is, please let me know and accept my apologies. However, it wasn't happening before this latest AE2 update, and searching @botania works fine. I also reverted to the previous Botania, and it still happens. So, really not sure which to report it to, and hopefully I made the right choice. :)

#### Environment
- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-3
- Forge Version: 2116
- Botania Version: r1.9-337
On SMP

Mod list: https://www.dropbox.com/s/xbk3sl3cnncjbdi/MODS.txt?dl=0

The log: https://gist.github.com/RealGrep/f97abd120fbed5de861d52a33adefbc8

**Comment by shartte** [comment]
Yeah we're trying to make facades out of floating flowers... aehem :o

As a temporary fix, you can open your Facades.cfg and set everything under the botania section to false.

**Comment by RealGrep** [comment]
Yay, made the right call! Thanks for the quick response, and the workaround. <3

**Comment by RealGrep** [comment]
That fixed it for that search. Was just in the process of searching "capacitor" for the EIO capacitor banks, and had another crash relating to facades:

https://gist.github.com/RealGrep/d145bc68f6b3e46afdcd4e6eebbe8c5c

Not too sure which facade caused that one, though. For one, I can't see the list that results from that search. heh

**Comment by MrGraphic** [comment]
You can also hide all facades via JEI's item hiding mode.

**Comment by shartte** [comment]
Ahem... Could you please delete your Facades.cfg and see if that fixes both of your issues?

**Comment by shartte** [comment]
Regardless of the possible config issue, I've fixed two other problems with facades, and also made the rendering more robust against uncooperative mods heh. 

There was an issue that only occured if one added mods to the game and then loaded up an old world. This might be the real cause for your issue here, in case you've added something like Botania after the fact. The Item IDs got shuffled and we were incorrectly storing item ids in the facade NBT. This causes problems because the creative tab is built in the main menu (and only once), but the item ids change meaning once an old world is loaded.

**Comment by RealGrep** [comment]
Yeah, I've gone from beta1 through beta3 and not deleted the AE2 configs, so if they didn't regenerate, they are probably from beta1. I'll zap them and let you know after the next server reboot if it fixes it. Botania's been in there forever, but it did just get upgraded.

Great to hear you've made the facade stuff more robust. Thanks for everything!

**Comment by RealGrep** [comment]
Both crashes still happen after deleting the entire config/AppliedEnergistics2 directory.

**Comment by shartte** [comment]
Could you try to make a new, empty world, and see if the problem also occurs in that world?

**Comment by RealGrep** [comment]
Searching for @applied and capacitor in a fresh world (having also deleted the AE2 configs on the client) does not crash. Sorry it took a bit, I couldn't get to it yesterday.

I assume the next update will prevent that and I won't have to zap and restart the world. Not the end of the world if I do have to, but would much rather not. :)

**Comment by shartte** [comment]
Next update will fix it in your existing world as well. Worst thing that'll happen is that it might zap some facades you have already placed and turn them into glass facades.
