### ISSUE TITLE
"Start" button non-functional when crafting vanilla cake

### ISSUE THREAD

**Issue by drstasis** [AppliedEnergistics/Applied-Energistics-2#2699]
#### Description
Clicking the "Start" button on the crafting screen does nothing when crafting cake. Works when crafting other items (sugar from sugarcane was tested on the same network.)
![ae2_issue](https://cloud.githubusercontent.com/assets/10377724/21088185/c0224e90-bfe1-11e6-9812-cad255e2ce26.png)
As seen in image, the "Start" button appears normal, but nothing happens when I click it.

#### Environment
Network is:
- ME controller
- Energy Acceptor providing AE from RF
- 1 Interface connected to a Molecular Assembler
- 3 Storage Buses connected to 3 separate storage drawers from Storage Drawers mod (version 1.10.2-3.4.2)
- 1 Storage Bus connected to an Oak Chest containing buckets of milk. Storage chest is configured to store empty buckets, milk buckets, and sugar (chest had 11 milk buckets at time of testing)
- 1 Crafting computer, composed of 1 Crafting Unit and 1 1k Crafting Storage
- 1 Export Bus, configured to export vanilla cake, upgraded with a Crafting Card (have tested with this disconnected.) As far as I know, this should be able to request a cake to be crafted.
- ME Crafting Terminal

- Minecraft Version: 1.10.2
- AE2 Version: rv4 alpha 5
- Forge Version: 12.18.2.2124

**Comment by Ommina** [comment]
I want to say this has already been fixed in a subsequent alpha.  You are, at present, three releases behind.  Maybe give alpha8 a try and see what that does for you.

**Comment by drstasis** [comment]
I will give that a shot when I can (travelling for work the next week or so)

**Comment by drstasis** [comment]
I had a chance to test some more today, so I upgraded to AE2 rv4 alpha 8 and Forge 12.18.2.2139. The issue remains: clicking the "Start" button does nothing. Screenshots of my test setup posted below.
![ae2_issue_creative1](https://cloud.githubusercontent.com/assets/10377724/21168803/ccddf978-c16b-11e6-9ed3-75116cbda637.png)
![ae2_issue_creative2](https://cloud.githubusercontent.com/assets/10377724/21168804/cce0536c-c16b-11e6-95cf-4977fce92e73.png)
![ae2_issue_creative3](https://cloud.githubusercontent.com/assets/10377724/21168805/cce764c2-c16b-11e6-8107-67aaefeeb87d.png)

I have attached a list of other mods I am running, perhaps there is a known interaction that is causing this.
[modlist.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/650753/modlist.txt)
