### ISSUE TITLE
Encoded Patterns not rendering recipe preview

### ISSUE THREAD

**Issue by dash16** [AppliedEnergistics/Applied-Energistics-2#5258]
**Describe the bug**
After installing appliedenergistics2-8.3.1, all of my encoded patterns are displaying the placeholder graphic of the encoded pattern, not the resulting output of the recipe.  Holding shift does temporarily display the recipe output, but disappears after letting go of shift.  This makes scrolling a large number of connected interfaces in the Pattern Terminal difficult as you can't scroll while holding shift.

**To Reproduce**

1. Install appliedenergistics2-8.3.1
2. Create an encoded pattern recipe.  Tested with vanilla crafting table
3. Observe the pattern icon.  Displays encoded pattern icon, not vanilla crafting table icon

**Expected behavior**
After encoding a valid recipe, the icon for the pattern should change to display the output item.  It only displays this while holding shift

**Additional context**
[default display](https://imgur.com/Eswqnel)
[holding shift](https://imgur.com/V6ZMrA5)

**Environment**
- Environment: forge-1.16.5-36.1.24
- The only other mod installed when testing was jei-1.16.5-7.7.0.100

**Comment by Technici4n** [comment]
Hello, thanks for the report! This is fixed starting from 8.4.0 - the GUIs were rewritten, and now this works correctly. Note that there have only been alphas so far, but I'm closing this as it's fixed.

**Comment by masakitenchi** [comment]
Hey there. I found that in ATM6-Skyblock this problem still occurs. Will this be fixed in a stable version rather than a beta version? I'm using 8.4.0beta2 right now.
![image](https://user-images.githubusercontent.com/11086210/121624651-dca63d80-caac-11eb-92bd-9598c34588ad.png)

**Comment by DoomSquirter** [comment]
I know this is closed and all but I thought it would be worth seeing if I could get an answer on this here before I go and create a issue for probably a codebase you all aren't updating anymore.

Having exact same issue as above, but I'm on 1.12 (appliedenergistics2-rv6-stable-7) which is a way way older version than you all are talking about here.  I swear this hasn't happened in other 1.12 packs and the latest for 1.12 is that version and is dated in 2019 so I doubt they are running any other version.
