### ISSUE TITLE
Storage bus causes a crash

### ISSUE THREAD

**Issue by Irutar** [AppliedEnergistics/Applied-Energistics-2#5930]
### Describe the bug

During autocrafting a game crashed and was closed. 

### How to reproduce the bug

Connect storage bus to MI device and order lots of items from it. In my case it is MI recepie for paper from wood pulp and water mixed in mixer. Both items are inserted from network into mixer via pattern provider -> interface -> storage bus. It happens very rearly. 

### Expected behavior

Game crash

Here are 3 crash reports that happened to me and are connected to storage bus. I also uploaded moste recent crash report to paste bin.

[crash-2021-12-24_14.39.07-server.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/7786480/crash-2021-12-24_14.39.07-server.txt)
[crash-2021-12-28_22.32.27-server.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/7786481/crash-2021-12-28_22.32.27-server.txt)
[crash-2021-12-23_19.27.21-server.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/7786482/crash-2021-12-23_19.27.21-server.txt)

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/L6M9Puv8

**Comment by mindforger** [comment]
Shouldn't this be fixed with https://github.com/AppliedEnergistics/Applied-Energistics-2/commit/d3841b98eb386fcd8a0513cb373677b7f9e5aa65 ?

**Comment by Irutar** [comment]
I have the latest version of both MI and AE2 so as you can see it is not fixed
